### Week (1)

In [1]:
# Important Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
import warnings
warnings.filterwarnings('ignore')
plt.show()

In [2]:
print("=" * 60)
print("  WEEK 1: Data Cleaning & Preprocessing")
print("=" * 60)

============================================================
  WEEK 1: Data Cleaning & Preprocessing
============================================================

In [3]:
# 1. Load all tables
emp = pd.read_csv('Employee.csv')
per = pd.read_csv('PerformanceRating.csv')
edu_level = pd.read_csv('EducationLevel.csv')
rating_level = pd.read_csv('RatingLevel.csv')
sat_level = pd.read_csv('SatisfiedLevel.csv')

In [4]:
print(f"Loaded Tables:")
print(f"  Employee          : {emp.shape}")
print(f"  PerformanceRating : {per.shape}")
print(f"  EducationLevel    : {edu_level.shape}")
print(f"  RatingLevel       : {rating_level.shape}")
print(f"  SatisfiedLevel    : {sat_level.shape}")

Loaded Tables:
  Employee          : (1470, 23)
  PerformanceRating : (6709, 11)
  EducationLevel    : (5, 2)
  RatingLevel       : (5, 2)
  SatisfiedLevel    : (5, 2)

In [5]:
# 2. Check duplicates & nulls
print(f"Null Values in Employee : {emp.isnull().sum().sum()}")
print(f"Duplicates in Employee : {emp.duplicated().sum()}\n")

print(f"Null Values in PerformanceRating : {per.isnull().sum().sum()}")
print(f"Duplicates in PerformanceRating : {per.duplicated().sum()}\n")

print(f"Null Values in EducationLevel : {edu_level.isnull().sum().sum()}")
print(f"Duplicates in EducationLevel : {edu_level.duplicated().sum()}\n")

print(f"Null Values in RatingLevel : {rating_level.isnull().sum().sum()}")
print(f"Duplicates in RatingLevel : {rating_level.duplicated().sum()}\n")

print(f"Null Values in SatisfiedLevel : {sat_level.isnull().sum().sum()}")
print(f"Duplicates in SatisfiedLevel : {sat_level.duplicated().sum()}\n")

Null Values in Employee : 0
Duplicates in Employee : 0

Null Values in PerformanceRating : 0
Duplicates in PerformanceRating : 0

Null Values in EducationLevel : 0
Duplicates in EducationLevel : 0

Null Values in RatingLevel : 0
Duplicates in RatingLevel : 0

Null Values in SatisfiedLevel : 0
Duplicates in SatisfiedLevel : 0

In [6]:
# 3. Parse dates
emp['HireDate'] = pd.to_datetime(emp['HireDate'])
per['ReviewDate'] = pd.to_datetime(per['ReviewDate'])

In [7]:
# 4. Fix string whitespace in lookup tables
edu_level['EducationLevel']   = edu_level['EducationLevel'].str.strip()
sat_level['SatisfactionLevel']  = sat_level['SatisfactionLevel'].str.strip()
rating_level['RatingLevel']     = rating_level['RatingLevel'].str.strip()

In [8]:
# 5. Build master dataframe
master = emp.merge(
    per, on = 'EmployeeID', how = 'left'
).merge(
    edu_level, left_on = 'Education', right_on = 'EducationLevelID', how = 'left'
).merge(
    rating_level.rename(columns = {'RatingID':'SelfRating','RatingLevel':'SelfRatingLabel'}),
    on = 'SelfRating', how = 'left'
).merge(
    rating_level.rename(columns = {'RatingID':'ManagerRating','RatingLevel':'ManagerRatingLabel'}),
    on = 'ManagerRating', how = 'left'
).merge(
    sat_level.rename(columns = {'SatisfactionID':'JobSatisfaction','SatisfactionLevel':'JobSatLabel'}),
    on = 'JobSatisfaction', how = 'left'
)

In [9]:
master.head()

,EmployeeID,FirstName,LastName,Gender,Age,BusinessTravel,Department,DistanceFromHome (KM),State,Ethnicity,...,TrainingOpportunitiesWithinYear,TrainingOpportunitiesTaken,WorkLifeBalance,SelfRating,ManagerRating,EducationLevelID,EducationLevel,SelfRatingLabel,ManagerRatingLabel,JobSatLabel
0,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,3.0,0.0,4.0,3.0,3.0,5,Doctorate,Meets Expectation,Meets Expectation,Neutral
1,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,3.0,1.0,2.0,3.0,2.0,5,Doctorate,Meets Expectation,Needs Improvement,Satisfied
2,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,3.0,0.0,4.0,5.0,5.0,5,Doctorate,Above and Beyond,Above and Beyond,Very Satisfied
3,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,3.0,1.0,3.0,5.0,4.0,5,Doctorate,Above and Beyond,Exceeds Expectation,Neutral
4,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,1.0,0.0,3.0,4.0,3.0,5,Doctorate,Exceeds Expectation,Meets Expectation,Satisfied

In [10]:
# 6. Derived columns
master['AttritionBinary'] = (master['Attrition'] == 'Yes').astype(int)
master['SalaryBand'] = pd.cut(master['Salary'],
    bins = [0, 50000, 80000, 110000, master['Salary'].max() + 1],
    labels = ['Low', 'Medium', 'High', 'Very High'])

In [11]:
master.head()

,EmployeeID,FirstName,LastName,Gender,Age,BusinessTravel,Department,DistanceFromHome (KM),State,Ethnicity,...,WorkLifeBalance,SelfRating,ManagerRating,EducationLevelID,EducationLevel,SelfRatingLabel,ManagerRatingLabel,JobSatLabel,AttritionBinary,SalaryBand
0,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,4.0,3.0,3.0,5,Doctorate,Meets Expectation,Meets Expectation,Neutral,0,High
1,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,2.0,3.0,2.0,5,Doctorate,Meets Expectation,Needs Improvement,Satisfied,0,High
2,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,4.0,5.0,5.0,5,Doctorate,Above and Beyond,Above and Beyond,Very Satisfied,0,High
3,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,3.0,5.0,4.0,5,Doctorate,Above and Beyond,Exceeds Expectation,Neutral,0,High
4,3012-1A41,Leonelle,Simco,Female,30,Some Travel,Sales,27,IL,White,...,3.0,4.0,3.0,5,Doctorate,Exceeds Expectation,Meets Expectation,Satisfied,0,High

In [12]:
print(" Week 1 Complete - Cleaned dataset is done")

 Week 1 Complete - Cleaned dataset is done